name: "Generate CLI"
description: "Generate Config Code"

inputs:
  repo:
    description: "Repository to generate code for"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.23"

    - name: Install dependencies
      shell: bash
      run: go mod download

    - name: Run generator
      shell: bash
      run: go run cmd/main.go
      env:
        CLI_REPO: ${{ inputs.repo }}
