on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate
        uses: dknathalage/cli/.github/actions/gen@main
        with:
          repo: dknathalage/cli
